### PR TITLE
Add tests from CUDAnative

### PR DESCRIPTION
**Pull request by jpsamaroo**
Copy a bunch of tests from CUDAnative
Don't export AS, addrspace to prevent conflicts
Clean up existing test a bit
Add AMDGPUNATIVE_DEBUG env. var for testing

I still have a bunch more tests to add, but this is the first set.

### CODE REVIEW

**Comment by jpsamaroo** [comment]
Once I've got most of the tests enabled and passing CI, what would you say to tagging and registering in General, @vchuravy ?

**Comment by jpsamaroo** [comment]
I'm going to skip adding the codegen tests for now because they're going to be a lot of work to support, I think.

**Comment by jpsamaroo** [comment]
Bump @vchuravy, any objections to merging this now to get slightly better test coverage?

**Comment by vchuravy** [comment]
No objections!

**Pull request merged**
