### PR TITLE
Make Gitlab CI green

### PR DESCRIPTION
**Pull request by jpsamaroo**
Uses changes made to HSARuntime to find a proper ld.lld binary

### CODE REVIEW

**Comment by jpsamaroo** [comment]
I believe once https://github.com/JuliaRegistries/Test/pull/31 merges we'll be good to go, since all the needed changes are in HSARuntime master.

**Comment by vchuravy** [comment]
The registrator is still in testing mode... So you could go through METADATA.jl

**Comment by jpsamaroo** [comment]
Lol I was wondering if those would actually end up in General... Will do

**Comment by jpsamaroo** [comment]
Alright, idk what's up with v1.0 failing to find ld.lld, since it definitely exists when I run the container locally. I'm willing to ignore it for now, in the name of glorious progress.

**Pull request merged**
